version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout    
      - setup_remote_docker
      - run: |
          
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
              docker tag app "quay.io/brice/dotnet-prometheus-example:${CIRCLE_SHA1}"
              docker push "quay.io/brice/dotnet-prometheus-example:${CIRCLE_SHA1}"
            fi